// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package types

type ChangePasswordRequest struct {
	Id          int64  `json:"id"`
	OldPassword string `json:"oldPassword"`
	NewPassword string `json:"newPassword"`
}

type ChangePasswordResponse struct {
	Success bool `json:"success"`
}

type GetUserInfoRequest struct {
	Id int64 `path:"id"`
}

type GetUserInfoResponse struct {
	UserInfo UserInfo `json:"userInfo"`
}

type LoginRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Token     string   `json:"token"`
	ExpiresAt int64    `json:"expiresAt"`
	UserInfo  UserInfo `json:"userInfo"`
}

type RegisterRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Email    string `json:"email"`
	Phone    string `json:"phone,omitempty"`
}

type RegisterResponse struct {
	Id       int64  `json:"id"`
	Username string `json:"username"`
	Email    string `json:"email"`
}

type Response struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type UpdateUserInfoRequest struct {
	Id       int64  `json:"id"`
	Phone    string `json:"phone,omitempty"`
	Avatar   string `json:"avatar,omitempty"`
	Gender   string `json:"gender,omitempty"`
	Birthday string `json:"birthday,omitempty"`
	Address  string `json:"address,omitempty"`
}

type UpdateUserInfoResponse struct {
	UserInfo UserInfo `json:"userInfo"`
}

type UserInfo struct {
	Id       int64  `json:"id"`
	Username string `json:"username"`
	Email    string `json:"email"`
	Phone    string `json:"phone,omitempty"`
	Avatar   string `json:"avatar,omitempty"`
	Gender   string `json:"gender,omitempty"` // male, female, other
	Birthday string `json:"birthday,omitempty"`
	Address  string `json:"address,omitempty"`
	CreateAt string `json:"createAt"`
	UpdateAt string `json:"updateAt"`
}
